import os
from datetime import time

PRIMARY_MODE = "NIFTY50_OPTIONS"
DEFAULT_SYMBOL = "NIFTY1.NS"         # Synced to TradingView NIFTY1! Futures
BTC_SYMBOL = "BTC-USD"               # Bitcoin Ticker
FOREX_SYMBOL = "EURUSD=X"            # EUR/USD Forex Ticker
VIX_SYMBOL = "^INDIAVIX"             # India VIX Ticker
TIMEFRAME = "15m"                    # 15-Minute Timeframe

# USER CAPITAL BUDGETING
BTC_START_CAPITAL_USD = 20.00        # $20.00 USD Starting Capital for Bitcoin
NIFTY_START_CAPITAL_INR = 2000.00    # ₹2,000.00 INR Starting Capital for NIFTY 50
FOREX_START_CAPITAL_USD = 100.00     # $100.00 USD Starting Capital for Forex

# NIFTY 15M MICRO-SCALP RISK PARAMETERS (RUPEES ₹)
NIFTY_LOT_SIZE = 25
DEFAULT_LOTS = 1
STOP_LOSS_POINTS = 10.0              # BUG G FIX: Widened SL 8→10 pts (-₹250/lot) to avoid noise exits
TARGET_1_POINTS = 18.0              # BUG G FIX: TP1 12→18 pts (+₹450/lot) → 1:1.8 R:R
TARGET_2_POINTS = 30.0              # BUG G FIX: TP2 25→30 pts (+₹750/lot) → 1:3.0 R:R
UNDERLYING_TARGET_NIFTY = 18.0

# BITCOIN 15M MICRO-SCALP RISK PARAMETERS ($ USD)
BTC_STOP_LOSS_PCT = 0.15             # Micro -0.15% Stop Loss (-$0.30 USD)
BTC_TARGET_1_PCT = 0.25              # Micro +0.25% Quick Target (+$0.50 USD)
BTC_TARGET_2_PCT = 0.50              # Micro +0.50% Trend Target (+$1.00 USD)

# FOREX 15M SCALP RISK PARAMETERS (PIPS & $ USD)
FOREX_STOP_LOSS_PIPS = 10.0          # -10 Pips SL (-$1.00 USD per 0.01 lot)
FOREX_TARGET_1_PIPS = 15.0           # +15 Pips TP1 (+$1.50 USD per 0.01 lot)
FOREX_TARGET_2_PIPS = 35.0           # +35 Pips TP2 (+$3.50 USD per 0.01 lot)

# STRICT 1-CANDLE EXPIRATION
MAX_HOLDING_CANDLES = 1

# 5-LAYER INSTITUTIONAL THRESHOLDS
MIN_HEAVYWEIGHT_K = 4
MIN_HEAVYWEIGHT_A = 0.75
MIN_VIX_BUY_THRESHOLD = 12.0
HIGH_VIX_THRESHOLD = 18.0
PCR_BULLISH_THRESHOLD = 1.10
PCR_BEARISH_THRESHOLD = 0.90
MIN_OI_RUNWAY_POINTS = 100.0
MIN_TARGET_COVERAGE_RATIO = 2.0

# CHAMPION FILTERS
MIN_15M_CANDLE_VOLUME = 50000
FIB_DISCOUNT_MIN = 0.705
FIB_DISCOUNT_MAX = 0.886
LUNCH_HOUR_START = time(11, 30)
LUNCH_HOUR_END = time(13, 30)

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")